language: node_js
node_js:
  - "8.10"
before_install:
  - npm install -g npm
  - npm install -g karma-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
deploy:
  email: amk528@cs.nyu.edu
  provider: npm
  api_key:
    secure: pEowAgsG9ULWrGt0cV+uP3Iq48GiC7qseB7I+LI0vcJdphy8hevCU/z8yJ9Q4pY/UJy9KvOcwlAtGdjmWXxeB7GUA8EfjcFImiFOEryog+ahuF1fCG8i5pZ6EACFcEq4CzBVnBdBSYFgZtMdS+wUSB2AstHEhB412bBLTa/q81Q=
notifications:
  email: false
